gcn:
  normalize_data: 'No'
  lr: 0.001
  weight_decay: 0.0
  dropout: 0.2
  num_layers: 2
  hidden: 64
  RPMAX: 10

gprgnn:
  normalize_data: 'No'
  lr: 0.005
  alpha: 1.0
  weight_decay: 0.0
  dprate: 0.2
  RPMAX: 10

gcn_denoise:
  normalize_data: 'No'
  lr: 0.001
  weight_decay: 0.0
  dropout: 0.2
  num_layers: 2
  hidden: 64
  abs_ordering: 'Yes'
  denoise_iterations: 17
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 38
  rewired_index_X: 109
  rewired_ratio_A: 0.07416545889876569
  rewired_ratio_X: 0.07902755557921515
  rewired_ratio_X_non_binary: 0.12876198796936733
  use_edge_attr: 'Yes'
  RPMAX: 10

gprgnn_denoise:
  normalize_data: 'No'
  lr: 0.005
  alpha: 1.0
  weight_decay: 0.0
  dprate: 0.2
  abs_ordering: 'Yes'
  denoise_iterations: 4
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 13
  rewired_index_X: 11
  rewired_ratio_A: 0.0013924521550920943
  rewired_ratio_X: 0.4650299476019481
  rewired_ratio_X_non_binary: 0.43128940474287014
  use_edge_attr: 'Yes'
  RPMAX: 10

rewire_ppr_gcn:
  rewire_alpha: 0.2
rewire_ppr_gprgnn:
  rewire_alpha: 0.6

rewire_borf:
  borf_num_iterations: 3
  borf_batch_add: 20
  borf_batch_remove: 40

rewire_borf_gprgnn:
  borf_num_iterations: 1
  borf_batch_add: 0
  borf_batch_remove: 30

rewire_fosr_gcn:
  fosr_num_iterations: 100
rewire_fosr_gprgnn:
  fosr_num_iterations: 600