gcn:
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  normalize_data: 'Yes'
  lr: 0.05
  weight_decay: 0.0



gprgnn:
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  normalize_data: 'No'
  lr: 0.05
  alpha: 1.0
  weight_decay: 0.0
  dprate: 0.7

gcn_denoise:
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  normalize_data: 'Yes'
  lr: 0.05
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 3
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 31
  rewired_index_X: 1331
  rewired_ratio_A: 0.06337266481028064
  rewired_ratio_X: 0.48562572918265784
  rewired_ratio_X_non_binary: 0.7551766260096617
  use_edge_attr: 'Yes'

gprgnn_denoise:
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  normalize_data: 'Yes'
  lr: 0.05
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 7
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 41
  rewired_index_X: 1099
  rewired_ratio_A: 0.06613668867536887
  rewired_ratio_X: 0.37461080303027305
  rewired_ratio_X_non_binary: 0.974530930615391
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  abs_ordering: 'Yes'
  denoise_iterations: 7
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 41
  rewired_index_X: 1099
  rewired_ratio_A: 0.06613668867536887
  rewired_ratio_X: 0.37461080303027305
  rewired_ratio_X_non_binary: 0.974530930615391
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn:
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  normalize_data: 'Yes'
  lr: 0.05
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 3
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 31
  rewired_index_X: 1331
  rewired_ratio_A: 0.06337266481028064
  rewired_ratio_X: 0.48562572918265784
  rewired_ratio_X_non_binary: 0.7551766260096617
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  normalize_data: 'Yes'
  lr: 0.05
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 3
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 31
  rewired_index_X: 1331
  rewired_ratio_A: 0.06337266481028064
  rewired_ratio_X: 0.48562572918265784
  rewired_ratio_X_non_binary: 0.7551766260096617
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  abs_ordering: 'Yes'
  denoise_iterations: 3
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 31
  rewired_index_X: 1331
  rewired_ratio_A: 0.06337266481028064
  rewired_ratio_X: 0.48562572918265784
  rewired_ratio_X_non_binary: 0.7551766260096617
  use_edge_attr: 'Yes'

rewire_borf:
  borf_num_iterations: 2
  borf_batch_add: 50
  borf_batch_remove: 30

rewire_borf_gprgnn:
  borf_num_iterations: 1
  borf_batch_add: 10
  borf_batch_remove: 30

rewire_borf_original:
  borf_num_iterations: 3
  borf_batch_add: 20
  borf_batch_remove: 20

rewire_ppr_gcn:
  rewire_alpha: 0.15
rewire_ppr_gprgnn:
  rewire_alpha: 0.5
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.55
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.4

rewire_fosr_gcn:
  fosr_num_iterations: 10
rewire_fosr_gprgnn:
  fosr_num_iterations: 5