gcn:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'

gprgnn:
  normalize_data: 'Yes'

mlp:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'

spectralclustering:

gcn_denoise:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1853
  rewired_index_X: 38
  rewired_ratio_A: 0.06617638216452848
  rewired_ratio_X: 0.1730490053534019
  rewired_ratio_X_non_binary: 0.07127345050296063
  use_edge_attr: 'Yes'

gprgnn_denoise:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1853
  rewired_index_X: 38
  rewired_ratio_A: 0.06617638216452848
  rewired_ratio_X: 0.1730490053534019
  rewired_ratio_X_non_binary: 0.07127345050296063
  use_edge_attr: 'Yes'

mlp_denoise:
  normalize_data: 'No'
  weight_decay_type: 'digl'
  weight_decay: 0.05
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1853
  rewired_index_X: 38
  rewired_ratio_A: 0.06617638216452848
  rewired_ratio_X: 0.1730490053534019
  rewired_ratio_X_non_binary: 0.07127345050296063
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1853
  rewired_index_X: 38
  rewired_ratio_A: 0.06617638216452848
  rewired_ratio_X: 0.1730490053534019
  rewired_ratio_X_non_binary: 0.07127345050296063
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 772
  rewired_index_X: 76
  rewired_ratio_A: 0.027171590003859936
  rewired_ratio_X: 0.43389828549151394
  rewired_ratio_X_non_binary: 0.0050034202294814145
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 772
  rewired_index_X: 76
  rewired_ratio_A: 0.027171590003859936
  rewired_ratio_X: 0.43389828549151394
  rewired_ratio_X_non_binary: 0.0050034202294814145
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 772
  rewired_index_X: 76
  rewired_ratio_A: 0.027171590003859936
  rewired_ratio_X: 0.43389828549151394
  rewired_ratio_X_non_binary: 0.0050034202294814145
  use_edge_attr: 'Yes'

gcn_denoise_dense:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1857
  rewired_index_X: 26
  rewired_ratio_A: 0.02316029338190367
  rewired_ratio_X: 0.02058656808360143
  rewired_ratio_X_non_binary: 0.6200119390885938
  use_edge_attr: 'Yes'

gprgnn_denoise_dense:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1857
  rewired_index_X: 26
  rewired_ratio_A: 0.02316029338190367
  rewired_ratio_X: 0.02058656808360143
  rewired_ratio_X_non_binary: 0.6200119390885938
  use_edge_attr: 'Yes'

mlp_denoise_dense:
  normalize_data: 'No'
  weight_decay_type: 'digl'
  weight_decay: 0.05
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1857
  rewired_index_X: 26
  rewired_ratio_A: 0.02316029338190367
  rewired_ratio_X: 0.02058656808360143
  rewired_ratio_X_non_binary: 0.6200119390885938
  use_edge_attr: 'Yes'

spectralclustering_denoise_dense:
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1857
  rewired_index_X: 26
  rewired_ratio_A: 0.02316029338190367
  rewired_ratio_X: 0.02058656808360143
  rewired_ratio_X_non_binary: 0.6200119390885938
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn_dense:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1467
  rewired_index_X: 14
  rewired_ratio_A: 0.014333179228152582
  rewired_ratio_X: 0.056367218617088544
  rewired_ratio_X_non_binary: 0.4586425000838524
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn_dense:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1467
  rewired_index_X: 14
  rewired_ratio_A: 0.014333179228152582
  rewired_ratio_X: 0.056367218617088544
  rewired_ratio_X_non_binary: 0.4586425000838524
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn_dense:
  weight_decay_type: 'digl'
  weight_decay: 0.05
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1467
  rewired_index_X: 14
  rewired_ratio_A: 0.014333179228152582
  rewired_ratio_X: 0.056367218617088544
  rewired_ratio_X_non_binary: 0.4586425000838524
  use_edge_attr: 'Yes'

rewire_borf_original:
  borf_num_iterations: 3
  borf_batch_add: 20
  borf_batch_remove: 10

rewire_borf2:
  borf_num_iterations: 2
  borf_batch_add: 10
  borf_batch_remove: 40

rewire_borf_gprgnn:
  borf_num_iterations: 2
  borf_batch_add: 30
  borf_batch_remove: 50

rewire_borf:
  borf_num_iterations: 2
  borf_batch_add: 30
  borf_batch_remove: 10

rewire_borf_dense:
  borf_num_iterations: 2
  borf_batch_add: 30
  borf_batch_remove: 10

rewire_borf_gprgnn_dense:
  borf_num_iterations: 1
  borf_batch_add: 10
  borf_batch_remove: 40

rewire_ppr_gcn:
  rewire_alpha: 0.1
rewire_ppr_gprgnn:
  rewire_alpha: 0.3
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.1
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.3

rewire_ppr_gcn_dense:
  rewire_alpha: 0.25
rewire_ppr_gprgnn_dense:
  rewire_alpha: 0.6
rewire_ppr_gcn_denoise_dense:
  rewire_alpha: 0.2
rewire_ppr_gprgnn_denoise_dense:
  rewire_alpha: 0.6