gcn:
  normalize_data: 'Yes'
  lr: 0.05

gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.9

gcn_denoise:
  normalize_data: 'Yes'
  lr: 0.05
  abs_ordering: 'Yes'
  denoise_iterations: 17
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 10
  rewired_index_X: 125
  rewired_ratio_A: 0.7944022854702982
  rewired_ratio_X: 0.29827867165311706
  rewired_ratio_X_non_binary: 0.11315841090987676
  use_edge_attr: 'Yes'

gprgnn_denoise:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.9
  abs_ordering: 'Yes'
  denoise_iterations: 17
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 10
  rewired_index_X: 125
  rewired_ratio_A: 0.7944022854702982
  rewired_ratio_X: 0.29827867165311706
  rewired_ratio_X_non_binary: 0.11315841090987676
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  abs_ordering: 'Yes'
  denoise_iterations: 17
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 10
  rewired_index_X: 125
  rewired_ratio_A: 0.7944022854702982
  rewired_ratio_X: 0.29827867165311706
  rewired_ratio_X_non_binary: 0.11315841090987676

gcn_denoise_gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  abs_ordering: 'Yes'
  denoise_iterations: 1
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 39
  rewired_index_X: 67
  rewired_ratio_A: 0.48224099972465945
  rewired_ratio_X: 0.4236419006100338
  rewired_ratio_X_non_binary: 0.06825329708424743
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.9
  abs_ordering: 'Yes'
  denoise_iterations: 1
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 39
  rewired_index_X: 67
  rewired_ratio_A: 0.48224099972465945
  rewired_ratio_X: 0.4236419006100338
  rewired_ratio_X_non_binary: 0.06825329708424743
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  abs_ordering: 'Yes'
  denoise_iterations: 1
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 39
  rewired_index_X: 67
  rewired_ratio_A: 0.48224099972465945
  rewired_ratio_X: 0.4236419006100338
  rewired_ratio_X_non_binary: 0.06825329708424743
  use_edge_attr: 'Yes'

rewire_borf_original:
  borf_num_iterations: 2
  borf_batch_add: 20
  borf_batch_remove: 30

rewire_borf:
  borf_num_iterations: 1
  borf_batch_add: 20
  borf_batch_remove: 50

rewire_borf_gprgnn:
  borf_num_iterations: 1
  borf_batch_add: 20
  borf_batch_remove: 50

rewire_ppr_gcn:
  rewire_alpha: 1.0
rewire_ppr_gprgnn:
  rewire_alpha: 1.0
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.95
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.0