gcn:
  lr: 0.01


gprgnn:
  lr: 0.01


gcn_denoise:
  denoise_iterations: 16
  denoise_offset: 0
  rewired_index_A: 10
  rewired_index_X: 8
  rewired_ratio_A: 0.034635509093338956
  rewired_ratio_X: 0.22768428736608404
  rewired_ratio_X_non_binary: 0.9811013900728272
  use_edge_attr: "Yes"

gprgnn_denoise:
  denoise_iterations: 16
  denoise_offset: 0
  rewired_index_A: 10
  rewired_index_X: 8
  rewired_ratio_A: 0.034635509093338956
  rewired_ratio_X: 0.22768428736608404
  rewired_ratio_X_non_binary: 0.9811013900728272
  use_edge_attr: "Yes"

spectralclustering_denoise:
  denoise_iterations: 16
  denoise_offset: 0
  rewired_index_A: 10
  rewired_index_X: 8
  rewired_ratio_A: 0.034635509093338956
  rewired_ratio_X: 0.22768428736608404
  rewired_ratio_X_non_binary: 0.9811013900728272
  use_edge_attr: "Yes"

mlp_denoise:
  denoise_iterations: 16
  denoise_offset: 0
  rewired_index_A: 10
  rewired_index_X: 8
  rewired_ratio_A: 0.034635509093338956
  rewired_ratio_X: 0.22768428736608404
  rewired_ratio_X_non_binary: 0.9811013900728272
  use_edge_attr: "Yes"

rewire_ppr_gcn:
  rewire_alpha: 0.05
rewire_ppr_gprgnn:
  rewire_alpha: 0.05