gcn:
  lr: 0.01


gprgnn:
  alpha: 1.0
  dprate: 0.7
  lr: 0.05

gcn_denoise:
  abs_ordering: "Yes"
  denoise_iterations: 50
  denoise_offset: 0
  rewired_index_A: 9
  rewired_index_X: 10
  rewired_ratio_A: 0.18898472944428957
  rewired_ratio_X: 0.4120705786826506
  rewired_ratio_X_non_binary: 0.9907039945845814
  use_edge_attr: "Yes"

gprgnn_denoise:
  alpha: 1.0
  dprate: 0.7
  lr: 0.05
  abs_ordering: "Yes"
  denoise_iterations: 50
  denoise_offset: 0
  rewired_index_A: 9
  rewired_index_X: 10
  rewired_ratio_A: 0.18898472944428957
  rewired_ratio_X: 0.4120705786826506
  rewired_ratio_X_non_binary: 0.9907039945845814
  use_edge_attr: "Yes"

spectralclustering_denoise:
  abs_ordering: "Yes"
  denoise_iterations: 50
  denoise_offset: 0
  rewired_index_A: 9
  rewired_index_X: 10
  rewired_ratio_A: 0.18898472944428957
  rewired_ratio_X: 0.4120705786826506
  rewired_ratio_X_non_binary: 0.9907039945845814
  use_edge_attr: "Yes"

mlp_denoise:
  abs_ordering: "Yes"
  denoise_iterations: 50
  denoise_offset: 0
  rewired_index_A: 9
  rewired_index_X: 10
  rewired_ratio_A: 0.18898472944428957
  rewired_ratio_X: 0.4120705786826506
  rewired_ratio_X_non_binary: 0.9907039945845814
  use_edge_attr: "Yes"

#gcn_denoise:
#  abs_ordering: "Yes"
#  denoise_iterations: 28
#  denoise_offset: 0
#  rewired_index_A: 7
#  rewired_index_X: 10
#  rewired_ratio_A: 0.24899785873274088
#  rewired_ratio_X: 0.4857251015243469
#  rewired_ratio_X_non_binary: 0.9524512669305504
#  use_edge_attr: "Yes"
#
#gprgnn_denoise:
#  alpha: 1.0
#  dprate: 0.7
#  lr: 0.05
#  abs_ordering: "Yes"
#  denoise_iterations: 28
#  denoise_offset: 0
#  rewired_index_A: 7
#  rewired_index_X: 10
#  rewired_ratio_A: 0.24899785873274088
#  rewired_ratio_X: 0.4857251015243469
#  rewired_ratio_X_non_binary: 0.9524512669305504
#  use_edge_attr: "Yes"
#
#spectralclustering_denoise:
#  abs_ordering: "Yes"
#  denoise_iterations: 28
#  denoise_offset: 0
#  rewired_index_A: 7
#  rewired_index_X: 10
#  rewired_ratio_A: 0.24899785873274088
#  rewired_ratio_X: 0.4857251015243469
#  rewired_ratio_X_non_binary: 0.9524512669305504
#  use_edge_attr: "Yes"
#
#mlp_denoise:
#  abs_ordering: "Yes"
#  denoise_iterations: 28
#  denoise_offset: 0
#  rewired_index_A: 7
#  rewired_index_X: 10
#  rewired_ratio_A: 0.24899785873274088
#  rewired_ratio_X: 0.4857251015243469
#  rewired_ratio_X_non_binary: 0.9524512669305504
#  use_edge_attr: "Yes"

rewire_ppr_gcn:
  rewire_alpha: 1.0
rewire_ppr_gprgnn:
  rewire_alpha: 1.0

rewire_fosr_gcn:
  fosr_num_iterations: 100
rewire_fosr_gprgnn:
  fosr_num_iterations: 600