gcn:
  lr: 0.01


gprgnn:
  alpha: 1.0
  dprate: 0.7
  lr: 0.05

gcn_denoise:
  abs_ordering: "Yes"
  denoise_iterations: 40
  denoise_offset: 0
  rewired_index_A: 6
  rewired_index_X: 9
  rewired_ratio_A: 0.04167156535338523
  rewired_ratio_X: 0.4978232364766541
  rewired_ratio_X_non_binary: 0.8464865841987947
  use_edge_attr: "Yes"

gprgnn_denoise:
  alpha: 1.0
  dprate: 0.7
  lr: 0.05
  abs_ordering: "Yes"
  denoise_iterations: 40
  denoise_offset: 0
  rewired_index_A: 6
  rewired_index_X: 9
  rewired_ratio_A: 0.04167156535338523
  rewired_ratio_X: 0.4978232364766541
  rewired_ratio_X_non_binary: 0.8464865841987947
  use_edge_attr: "Yes"

spectralclustering_denoise:
  abs_ordering: "Yes"
  denoise_iterations: 40
  denoise_offset: 0
  rewired_index_A: 6
  rewired_index_X: 9
  rewired_ratio_A: 0.04167156535338523
  rewired_ratio_X: 0.4978232364766541
  rewired_ratio_X_non_binary: 0.8464865841987947
  use_edge_attr: "Yes"

mlp_denoise:
  abs_ordering: "Yes"
  denoise_iterations: 40
  denoise_offset: 0
  rewired_index_A: 6
  rewired_index_X: 9
  rewired_ratio_A: 0.04167156535338523
  rewired_ratio_X: 0.4978232364766541
  rewired_ratio_X_non_binary: 0.8464865841987947
  use_edge_attr: "Yes"

rewire_ppr_gcn:
  rewire_alpha: 1.0
rewire_ppr_gprgnn:
  rewire_alpha: 1.0