gcn:
  normalize_data: 'No'
  early_stop_type: 'digl'
  early_stop_loss: 'acc'


gprgnn:
  normalize_data: 'Yes'
  alpha: 0.9
  weight_decay: 0.0

gcn_denoise:
  normalize_data: 'No'
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  abs_ordering: 'Yes'
  denoise_iterations: 29
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 896
  rewired_index_X: 14
  rewired_ratio_A: 0.2977718472355053
  rewired_ratio_X: 0.2345075814528786
  rewired_ratio_X_non_binary: 0.21895954946442583
  use_edge_attr: 'Yes'

gprgnn_denoise:
  normalize_data: 'Yes'
  alpha: 0.9
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 29
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 896
  rewired_index_X: 14
  rewired_ratio_A: 0.2977718472355053
  rewired_ratio_X: 0.2345075814528786
  rewired_ratio_X_non_binary: 0.21895954946442583
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  abs_ordering: 'Yes'
  denoise_iterations: 29
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 896
  rewired_index_X: 14
  rewired_ratio_A: 0.2977718472355053
  rewired_ratio_X: 0.2345075814528786
  rewired_ratio_X_non_binary: 0.21895954946442583
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn:
  normalize_data: 'No'
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  abs_ordering: 'Yes'
  denoise_iterations: 11
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1171
  rewired_index_X: 791
  rewired_ratio_A: 0.47560425628716174
  rewired_ratio_X: 0.02833953077133672
  rewired_ratio_X_non_binary: 0.2506666737534141
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  normalize_data: 'Yes'
  alpha: 0.9
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 11
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1171
  rewired_index_X: 791
  rewired_ratio_A: 0.47560425628716174
  rewired_ratio_X: 0.02833953077133672
  rewired_ratio_X_non_binary: 0.2506666737534141
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  abs_ordering: 'Yes'
  denoise_iterations: 11
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1171
  rewired_index_X: 791
  rewired_ratio_A: 0.47560425628716174
  rewired_ratio_X: 0.02833953077133672
  rewired_ratio_X_non_binary: 0.2506666737534141
  use_edge_attr: 'Yes'

rewire_borf:
  borf_num_iterations: 2
  borf_batch_add: 40
  borf_batch_remove: 50

rewire_borf_gprgnn:
  borf_num_iterations: 2
  borf_batch_add: 10
  borf_batch_remove: 50

rewire_ppr_gcn:
  rewire_alpha: 1.0
rewire_ppr_gprgnn:
  rewire_alpha: 0.6
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.2
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.05

rewire_fosr_gcn:
  fosr_num_iterations: 10
rewire_fosr_gprgnn:
  fosr_num_iterations: 150