gcn:
  normalize_data: 'No'
  lr: 0.005
  weight_decay: 0.0
  dropout: 0.2
  RPMAX: 10

gprgnn:
  normalize_data: 'No'
  lr: 0.005
  alpha: 1.0
  weight_decay: 0.0
  dprate: 0.2
  RPMAX: 10

gcn_denoise:
  normalize_data: 'No'
  lr: 0.005
  weight_decay: 0.0
  dropout: 0.2
  abs_ordering: 'No'
  denoise_iterations: 8
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 5
  rewired_index_X: 2
  rewired_ratio_A: 0.4500401113433711
  rewired_ratio_X: 0.26397657628411886
  rewired_ratio_X_non_binary: 0.11867246323089342
  use_edge_attr: 'Yes'
  denoise_A_k: 45
  RPMAX: 10

gprgnn_denoise_gprgnn:
  normalize_data: 'No'
  lr: 0.005
  alpha: 1.0
  weight_decay: 0.0
  dprate: 0.2
  abs_ordering: 'No'
  denoise_iterations: 10
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 3
  rewired_index_X: 1
  rewired_ratio_A: 0.4630015549848262
  rewired_ratio_X: 0.016833423457425667
  rewired_ratio_X_non_binary: 0.7336108658443317
  use_edge_attr: 'Yes'
  denoise_A_k: 41
  RPMAX: 10

rewire_ppr_gcn:
  rewire_alpha: 0.5
rewire_ppr_gprgnn:
  rewire_alpha: 0.5

rewire_borf:
  borf_num_iterations: 1
  borf_batch_add: 10
  borf_batch_remove: 10

rewire_borf_gprgnn:
  borf_num_iterations: 1
  borf_batch_add: 20
  borf_batch_remove: 10

rewire_fosr_gcn:
  fosr_num_iterations: 100
rewire_fosr_gprgnn:
  fosr_num_iterations: 5