gcn:
  normalize_data: 'No'

gprgnn:
  normalize_data: 'No'
  alpha: 0.5
  weight_decay: 0.0

spectralclustering:

gcn_denoise:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 6
  rewired_index_A: 467
  rewired_index_X: 1867
  rewired_ratio_A: 0.47876709555894303
  rewired_ratio_X: 0.07080250297320978
  rewired_ratio_X_non_binary: 0.34382001406079066
  use_edge_attr: 'Yes'

gprgnn_denoise:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  alpha: 0.5
  weight_decay: 0.0
  denoise_type: 'jointly'
  denoise_iterations: 6
  rewired_index_A: 467
  rewired_index_X: 1867
  rewired_ratio_A: 0.47876709555894303
  rewired_ratio_X: 0.07080250297320978
  rewired_ratio_X_non_binary: 0.34382001406079066
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 6
  rewired_index_A: 467
  rewired_index_X: 1867
  rewired_ratio_A: 0.47876709555894303
  rewired_ratio_X: 0.07080250297320978
  rewired_ratio_X_non_binary: 0.34382001406079066
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 4
  rewired_index_A: 433
  rewired_index_X: 1719
  rewired_ratio_A: 0.4129790105374149
  rewired_ratio_X: 0.11539506369242114
  rewired_ratio_X_non_binary: 0.23121395303184444
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  alpha: 0.5
  weight_decay: 0.0
  denoise_type: 'jointly'
  denoise_iterations: 4
  rewired_index_A: 433
  rewired_index_X: 1719
  rewired_ratio_A: 0.4129790105374149
  rewired_ratio_X: 0.11539506369242114
  rewired_ratio_X_non_binary: 0.23121395303184444
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 4
  rewired_index_A: 433
  rewired_index_X: 1719
  rewired_ratio_A: 0.4129790105374149
  rewired_ratio_X: 0.11539506369242114
  rewired_ratio_X_non_binary: 0.23121395303184444
  use_edge_attr: 'Yes'

gcn_denoise_dense:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 6
  rewired_index_A: 430
  rewired_index_X: 482
  rewired_ratio_A: 0.37440288218598367
  rewired_ratio_X: 0.1520349936653776
  rewired_ratio_X_non_binary: 0.11596623906096304
  use_edge_attr: 'Yes'

gprgnn_denoise_dense:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  alpha: 0.5
  weight_decay: 0.0
  denoise_type: 'jointly'
  denoise_iterations: 6
  rewired_index_A: 430
  rewired_index_X: 482
  rewired_ratio_A: 0.37440288218598367
  rewired_ratio_X: 0.1520349936653776
  rewired_ratio_X_non_binary: 0.11596623906096304
  use_edge_attr: 'Yes'

spectralclustering_denoise_dense:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 6
  rewired_index_A: 430
  rewired_index_X: 482
  rewired_ratio_A: 0.37440288218598367
  rewired_ratio_X: 0.1520349936653776
  rewired_ratio_X_non_binary: 0.11596623906096304
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn_dense:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 3
  rewired_index_A: 440
  rewired_index_X: 512
  rewired_ratio_A: 0.08638595723925718
  rewired_ratio_X: 0.4971948458107113
  rewired_ratio_X_non_binary: 0.3676498250484955
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn_dense:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  alpha: 0.5
  weight_decay: 0.0
  denoise_type: 'jointly'
  denoise_iterations: 3
  rewired_index_A: 440
  rewired_index_X: 512
  rewired_ratio_A: 0.08638595723925718
  rewired_ratio_X: 0.4971948458107113
  rewired_ratio_X_non_binary: 0.3676498250484955
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn_dense:
  normalize_data: 'No'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  denoise_iterations: 3
  rewired_index_A: 440
  rewired_index_X: 512
  rewired_ratio_A: 0.08638595723925718
  rewired_ratio_X: 0.4971948458107113
  rewired_ratio_X_non_binary: 0.3676498250484955
  use_edge_attr: 'Yes'

rewire_borf:
  borf_num_iterations: 3
  borf_batch_add: 0
  borf_batch_remove: 50

rewire_borf_gprgnn:
  borf_num_iterations: 3
  borf_batch_add: 10
  borf_batch_remove: 20

rewire_borf_dense:
  borf_num_iterations: 2
  borf_batch_add: 40
  borf_batch_remove: 20

rewire_borf_gprgnn_dense:
  borf_num_iterations: 3
  borf_batch_add: 50
  borf_batch_remove: 50

rewire_ppr_gcn:
  rewire_alpha: 0.2
rewire_ppr_gprgnn:
  rewire_alpha: 0.5
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.1
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.5

rewire_ppr_gcn_dense:
  rewire_alpha: 0.3
rewire_ppr_gprgnn_dense:
  rewire_alpha: 0.7
rewire_ppr_gcn_denoise_dense:
  rewire_alpha: 0.2
rewire_ppr_gprgnn_denoise_dense:
  rewire_alpha: 0.75

rewire_fosr_gcn:
  fosr_num_iterations: 5
rewire_fosr_gprgnn:
  fosr_num_iterations: 500

rewire_fosr_gcn_dense:
  fosr_num_iterations: 25
rewire_fosr_gprgnn_dense:
  fosr_num_iterations: 250