gcn:
  normalize_data: 'Yes'


gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.2

spectralclustering:

gcn_denoise:
  denoise_iterations: 12
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 8
  rewired_index_X: 53
  rewired_ratio_A: 0.3157896827492562
  rewired_ratio_X: 0.003535707586030279
  rewired_ratio_X_non_binary: 0.18717144758047133
  use_edge_attr: 'Yes'

gprgnn_denoise:
  denoise_iterations: 12
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 8
  rewired_index_X: 53
  rewired_ratio_A: 0.3157896827492562
  rewired_ratio_X: 0.003535707586030279
  rewired_ratio_X_non_binary: 0.18717144758047133
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  denoise_iterations: 12
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 8
  rewired_index_X: 53
  rewired_ratio_A: 0.3157896827492562
  rewired_ratio_X: 0.003535707586030279
  rewired_ratio_X_non_binary: 0.18717144758047133
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn:
  denoise_iterations: 1
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1772
  rewired_index_X: 919
  rewired_ratio_A: 0.1971571184518056
  rewired_ratio_X: 0.8931744479435921
  rewired_ratio_X_non_binary: 0.03410451303614859
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  denoise_iterations: 1
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1772
  rewired_index_X: 919
  rewired_ratio_A: 0.1971571184518056
  rewired_ratio_X: 0.8931744479435921
  rewired_ratio_X_non_binary: 0.03410451303614859
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  denoise_iterations: 1
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1772
  rewired_index_X: 919
  rewired_ratio_A: 0.1971571184518056
  rewired_ratio_X: 0.8931744479435921
  rewired_ratio_X_non_binary: 0.03410451303614859
  use_edge_attr: 'Yes'

gcn_denoise_dense:
  denoise_iterations: 1
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1861
  rewired_index_X: 16
  rewired_ratio_A: 0.03671331046037162
  rewired_ratio_X: 0.3488570315713922
  rewired_ratio_X_non_binary: 0.942301531708647
  use_edge_attr: 'Yes'

gprgnn_denoise_dense:
  denoise_iterations: 1
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1861
  rewired_index_X: 16
  rewired_ratio_A: 0.03671331046037162
  rewired_ratio_X: 0.3488570315713922
  rewired_ratio_X_non_binary: 0.942301531708647
  use_edge_attr: 'Yes'

spectralclustering_denoise_dense:
  denoise_iterations: 1
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1861
  rewired_index_X: 16
  rewired_ratio_A: 0.03671331046037162
  rewired_ratio_X: 0.3488570315713922
  rewired_ratio_X_non_binary: 0.942301531708647
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn_dense:
  denoise_iterations: 2
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1718
  rewired_index_X: 133
  rewired_ratio_A: 0.07823871157754125
  rewired_ratio_X: 0.2519613489156988
  rewired_ratio_X_non_binary: 0.026191773786636507
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn_dense:
  denoise_iterations: 2
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1718
  rewired_index_X: 133
  rewired_ratio_A: 0.07823871157754125
  rewired_ratio_X: 0.2519613489156988
  rewired_ratio_X_non_binary: 0.026191773786636507
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn_dense:
  denoise_iterations: 2
  normalize_data: 'Yes'
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 1718
  rewired_index_X: 133
  rewired_ratio_A: 0.07823871157754125
  rewired_ratio_X: 0.2519613489156988
  rewired_ratio_X_non_binary: 0.026191773786636507
  use_edge_attr: 'Yes'

rewire_borf:
  borf_num_iterations: 2
  borf_batch_add: 0
  borf_batch_remove: 30

rewire_borf_gprgnn:
  borf_num_iterations: 3
  borf_batch_add: 20
  borf_batch_remove: 40

rewire_borf_dense:
  borf_num_iterations: 2
  borf_batch_add: 0
  borf_batch_remove: 30

rewire_borf_gprgnn_dense:
  borf_num_iterations: 3
  borf_batch_add: 20
  borf_batch_remove: 40

rewire_ppr_gcn:
  rewire_alpha: 0.35
rewire_ppr_gprgnn:
  rewire_alpha: 0.6
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.4
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.6

rewire_ppr_gcn_dense:
  rewire_alpha: 0.6
rewire_ppr_gprgnn_dense:
  rewire_alpha: 0.5
rewire_ppr_gcn_denoise_dense:
  rewire_alpha: 0.6
rewire_ppr_gprgnn_denoise_dense:
  rewire_alpha: 0.65

rewire_fosr_gcn:
  fosr_num_iterations: 50
rewire_fosr_gprgnn:
  fosr_num_iterations: 175

rewire_fosr_gcn_dense:
  fosr_num_iterations: 10
rewire_fosr_gprgnn_dense:
  fosr_num_iterations: 5