gcn:
  early_stop_type: 'digl'
  normalize_data: 'Yes'
  early_stop_loss: 'acc'
  lr: 0.05
  weight_decay: 0.0

mlp:
  normalize_data: 'Yes'

gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.0
  weight_decay: 0.0
  dprate: 0.7

gcn_denoise:
  early_stop_type: 'digl'
  normalize_data: 'Yes'
  early_stop_loss: 'acc'
  lr: 0.05
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 4
  rewired_index_X: 1941
  rewired_ratio_A: 0.40374436460978913
  rewired_ratio_X: 0.010960372771840863
  rewired_ratio_X_non_binary: 0.0216644760822563
  use_edge_attr: 'Yes'

gprgnn_denoise:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.0
  weight_decay: 0.0
  dprate: 0.7
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  abs_ordering: 'Yes'
  denoise_iterations: 2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 4
  rewired_index_X: 1941
  rewired_ratio_A: 0.40374436460978913
  rewired_ratio_X: 0.010960372771840863
  rewired_ratio_X_non_binary: 0.0216644760822563
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  abs_ordering: 'Yes'
  denoise_iterations: 2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 4
  rewired_index_X: 1941
  rewired_ratio_A: 0.40374436460978913
  rewired_ratio_X: 0.010960372771840863
  rewired_ratio_X_non_binary: 0.0216644760822563
  use_edge_attr: 'Yes'

mlp_denoise:
  abs_ordering: 'Yes'
  denoise_iterations: 2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 4
  rewired_index_X: 1941
  rewired_ratio_A: 0.40374436460978913
  rewired_ratio_X: 0.010960372771840863
  rewired_ratio_X_non_binary: 0.0216644760822563
  use_edge_attr: 'Yes'

gcn_denoise_gprgnn:
  early_stop_type: 'digl'
  normalize_data: 'Yes'
  early_stop_loss: 'acc'
  lr: 0.05
  weight_decay: 0.0
  abs_ordering: 'Yes'
  denoise_iterations: 2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 53
  rewired_index_X: 1210
  rewired_ratio_A: 0.23385697433373392
  rewired_ratio_X: 0.49505692197817214
  rewired_ratio_X_non_binary: 0.9641364814314056
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 0.0
  weight_decay: 0.0
  dprate: 0.7
  early_stop_type: 'digl'
  early_stop_loss: 'acc'
  abs_ordering: 'Yes'
  denoise_iterations: 2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 53
  rewired_index_X: 1210
  rewired_ratio_A: 0.23385697433373392
  rewired_ratio_X: 0.49505692197817214
  rewired_ratio_X_non_binary: 0.9641364814314056
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  abs_ordering: 'Yes'
  denoise_iterations: 2
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 53
  rewired_index_X: 1210
  rewired_ratio_A: 0.23385697433373392
  rewired_ratio_X: 0.49505692197817214
  rewired_ratio_X_non_binary: 0.9641364814314056
  use_edge_attr: 'Yes'

#rewire_borf:
#  borf_num_iterations: 2
#  borf_batch_add: 40
#  borf_batch_remove: 50

rewire_ppr_gcn:
  rewire_alpha: 0.05
rewire_ppr_gprgnn:
  rewire_alpha: 0.15
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.1
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.2