gcn:
  normalize_data: 'Yes'
  lr: 0.05


gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 1.0

gcn_denoise:
  normalize_data: 'Yes'
  lr: 0.05
  abs_ordering: 'No'
  denoise_iterations: 20
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 21
  rewired_index_X: 183
  rewired_ratio_A: 0.5138169562184633
  rewired_ratio_X: 0.028104766857688212
  rewired_ratio_X_non_binary: 0.8362577751788685
  use_edge_attr: 'Yes'

gprgnn_denoise:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 1.0
  abs_ordering: 'No'
  denoise_iterations: 20
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 21
  rewired_index_X: 183
  rewired_ratio_A: 0.5138169562184633
  rewired_ratio_X: 0.028104766857688212
  rewired_ratio_X_non_binary: 0.8362577751788685
  use_edge_attr: 'Yes'

spectralclustering_denoise:
  abs_ordering: 'No'
  denoise_iterations: 20
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 21
  rewired_index_X: 183
  rewired_ratio_A: 0.5138169562184633
  rewired_ratio_X: 0.028104766857688212
  rewired_ratio_X_non_binary: 0.8362577751788685

gcn_denoise_gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  abs_ordering: 'Yes'
  denoise_iterations: 1
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 109
  rewired_index_X: 36
  rewired_ratio_A: 0.18226015435314885
  rewired_ratio_X: 0.003671605785029908
  rewired_ratio_X_non_binary: 0.2138978175473749
  use_edge_attr: 'Yes'

gprgnn_denoise_gprgnn:
  normalize_data: 'Yes'
  lr: 0.05
  alpha: 1.0
  abs_ordering: 'Yes'
  denoise_iterations: 1
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 109
  rewired_index_X: 36
  rewired_ratio_A: 0.18226015435314885
  rewired_ratio_X: 0.003671605785029908
  rewired_ratio_X_non_binary: 0.2138978175473749
  use_edge_attr: 'Yes'

spectralclustering_denoise_gprgnn:
  abs_ordering: 'Yes'
  denoise_iterations: 1
  denoise_non_binary: 'Yes'
  denoise_type: 'jointly'
  rewired_index_A: 109
  rewired_index_X: 36
  rewired_ratio_A: 0.18226015435314885
  rewired_ratio_X: 0.003671605785029908
  rewired_ratio_X_non_binary: 0.2138978175473749
  use_edge_attr: 'Yes'

rewire_borf:
  borf_num_iterations: 1
  borf_batch_add: 40
  borf_batch_remove: 10

rewire_borf_gprgnn:
  borf_num_iterations: 2
  borf_batch_add: 40
  borf_batch_remove: 50

rewire_borf_original:
  borf_num_iterations: 3
  borf_batch_add: 30
  borf_batch_remove: 10

rewire_ppr_gcn:
  rewire_alpha: 1.0
rewire_ppr_gprgnn:
  rewire_alpha: 0.0
rewire_ppr_gcn_denoise:
  rewire_alpha: 0.2
rewire_ppr_gprgnn_denoise:
  rewire_alpha: 0.2